Merge forward and central into one method
ZidongLiu/FedDisco pull request #37
Opened 2024-08-30 04:43 UTC by BichengYing

it should simplified the on-fly-perturb impl. I didn't run the code one real machine, please double check, thanks!

2024-08-30 14:01 UTC, ZidongLiu commented on gradient_estimators/random_gradient_estimator.py
> +            dir_grad = (pert_plus_loss - pert_minus_loss) / self.mu
/ self.mu / 2 for central
/ self.mu for forward

2024-08-30 14:15 UTC, ZidongLiu requested changes
1. feel some work might also need to happen in cezo_fl/shared.py.
2. divide by 2 times mu for central method

2024-08-30 14:15 UTC, ZidongLiu commented on gradient_estimators/random_gradient_estimator.py
> +            dir_grad = (pert_plus_loss - pert_minus_loss) / self.mu
```suggestion
    if self.grad_estimate_method == "central":
            dir_grad = (pert_plus_loss - pert_minus_loss) / ( 2 * self.mu)
    else:
            dir_grad = (pert_plus_loss - pert_minus_loss) / self.mu
```

2024-08-30 18:41 UTC, BichengYing commented on gradient_estimators/random_gradient_estimator.py
> +            dir_grad = (pert_plus_loss - pert_minus_loss) / self.mu
good catch!

2024-08-30 18:42 UTC, BichengYing commented
> 1. feel some work might also need to happen in cezo_fl/shared.py.

I checked the code. I didn't find any because there is no place explicitly calling `_forward_method` or `_central_method`. Can you double check?

2024-08-31 14:01 UTC, ZidongLiu approved these changes
> > 1. feel some work might also need to happen in cezo_fl/shared.py.
> 
> I checked the code. I didn't find any because there is no place explicitly calling `_forward_method` or `_central_method`. Can you double check?

Thought you are implementing layer-wise perturbation. LGTM

2024-08-31 14:20 UTC, ZidongLiu commented
for 1 clients/ 1 sample/ 1 perturb: 
![image](https://github.com/user-attachments/assets/c80f137e-6401-45ea-96fb-4d7e8a8f965b)
central works
![image](https://github.com/user-attachments/assets/b2048782-d927-4c9e-ad79-8fb3f9f78fa2)
forward works 

for 3 client / 2 sample / 5 perturb:
![image](https://github.com/user-attachments/assets/6f2e2089-8e92-4650-b71e-c4d6738f21e1)
central works

![image](https://github.com/user-attachments/assets/31a4e33e-4457-4fd3-96b1-6f15c687bdc9)
forawrd works and is faster than central

2024-08-31 14:21 UTC, merged

2024-08-31 16:35 UTC, BichengYing commented
why the speed in first two figure got slower and slower??